name: Daily Sentiment Update

on:
  workflow_dispatch:    # allows you to click “Run workflow” manually
  schedule:
    - cron: '0 14 * * *'
    - cron: '0 15 * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Generate config.json from your Secrets
      - name: Write config.json
        run: |
          cat <<EOF > config.json
          {
            "metabase": {
              "url": "${{ secrets.METABASE_URL }}",
              "username": "${{ secrets.METABASE_USER }}",
              "password": "${{ secrets.METABASE_PASS }}"
            },
            "metabase_question_id": 3231,
            "google_sheets": {
              "spreadsheet_id": "${{ secrets.SHEET_ID }}",
              "credentials_path": "credentials/gsheets-service.json"
            }
          }
          EOF

      # Create the credentials folder and inject your service‐account JSON
      - name: Write Google creds
        run: |
          mkdir -p credentials
          echo "${{ secrets.GCREDS_JSON }}" > credentials/gsheets-service.json

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run workflow
        run: python workflow.py
