name: Daily Sentiment Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * *'
    - cron: '0 15 * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Write config.json
        run: |
          cat <<EOF > config.json
          {
            "metabase": {
              "url": "${{ secrets.METABASE_URL }}",
              "username": "${{ secrets.METABASE_USER }}",
              "password": "${{ secrets.METABASE_PASS }}"
            },
            "metabase_question_id": 3231,
            "google_sheets": {
              "spreadsheet_id": "${{ secrets.SHEET_ID }}",
              "credentials_path": "credentials/gsheets-service.json"
            }
          }
          EOF

      - name: Write Google creds
        env:
          GCREDS_JSON: "${{ secrets.GCREDS_JSON }}"
        run: |
          mkdir -p credentials
          printf "%s" "$GCREDS_JSON" > credentials/gsheets-service.json

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run workflow
        run: python workflow.py
